// <auto-generated />
namespace BoVoyageTest.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BaseLocale : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BaseLocale));
        
        string IMigrationMetadata.Id
        {
            get { return "201807090910484_BaseLocale"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
